/**
 * The connector's `[[routes]]` for a manifest: one terminated route per door,
 * one price each, in the exact TOML shape the Rust connector loads. Append the
 * output to the node's config and restart the connector.
 */
import { type Manifest, doorAddress } from './doors.js';

export interface RoutesOptions {
  /** Where the connector reaches the forwarder, e.g. `http://forwarder:3700`. */
  handlerHost: string;
  /** Override the manifest prefix, e.g. when the same doors hang under another operator's address space. */
  prefix?: string;
}

export function routesToml(m: Manifest, o: RoutesOptions): string {
  const host = o.handlerHost.replace(/\/+$/, '');
  const prefix = o.prefix ?? m.prefix;
  const lines: string[] = [
    `# ${m.title}: ${m.doors.length} doors under ${prefix}, generated by \`toon-checkout routes\`.`,
    `# One door per price: the connector refuses one handler_url at two prices, and a`,
    `# reject is still charged, so each door sells exactly what its path delivers.`,
    `# handler_url carries a path: the envelope's target resolves beneath it.`,
    '',
  ];
  for (const d of m.doors) {
    lines.push(`# ${d.title} (${d.method} ${d.path})`);
    lines.push('[[routes]]');
    lines.push(`prefix = "${doorAddress(m, d, prefix)}"`);
    lines.push(`handler_url = "${host}${d.path}"`);
    lines.push(`price = ${d.units}`);
    lines.push('');
  }
  return lines.join('\n');
}

/** The `[node] addresses` list a manifest implies. */
export const addressesToml = (m: Manifest, prefix = m.prefix) => `addresses = [${m.doors.map((d) => `"${doorAddress(m, d, prefix)}"`).join(', ')}]`;
